export default {
  "login": "Rayeeskha",
  "id": 55346459,
  "node_id": "MDQ6VXNlcjU1MzQ2NDU5",
  "avatar_url": "https://avatars3.githubusercontent.com/u/55346459?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Rayeeskha",
  "html_url": "https://github.com/Rayeeskha",
  "followers_url": "https://api.github.com/users/Rayeeskha/followers",
  "following_url": "https://api.github.com/users/Rayeeskha/following{/other_user}",
  "gists_url": "https://api.github.com/users/Rayeeskha/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Rayeeskha/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Rayeeskha/subscriptions",
  "organizations_url": "https://api.github.com/users/Rayeeskha/orgs",
  "repos_url": "https://api.github.com/users/Rayeeskha/repos",
  "events_url": "https://api.github.com/users/Rayeeskha/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Rayeeskha/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Rayees khan",
  "company": null,
  "blog": "http://khanrayees.000webhostapp.com/",
  "location": "Hyderabad",
  "email": null,
  "hireable": null,
  "bio": "Fullstack Software  Developer & Blogger",
  "twitter_username": null,
  "public_repos": 27,
  "public_gists": 0,
  "followers": 1,
  "following": 3,
  "created_at": "2019-09-15T09:34:29Z",
  "updated_at": "2020-11-11T15:38:49Z"
};
